### Authentication Endpoints

### Register new user
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "email": "ugur@gmail.com",
    "password": "deneme"
}

### Login
POST http://localhost:8000/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=ugur@gmail.com&password=deneme

### User Management Endpoints

### Get all users
GET http://localhost:8000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODI0NTQxMn0.PuQMzGRbI7QK425PfGRO8VN-FK0MHqP2Wg6XFyajXdI

### Get specific user
GET http://localhost:8000/api/users/settings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODI0NTQxMn0.PuQMzGRbI7QK425PfGRO8VN-FK0MHqP2Wg6XFyajXdI

### Update user
PUT http://localhost:8000/api/users/settings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODI0NTQxMn0.PuQMzGRbI7QK425PfGRO8VN-FK0MHqP2Wg6XFyajXdI

{
    "export_location": "/home/testuser/mertloadtest",
    "export_type": "csv",
    "max_parallel_queries": 3,
    "ssh_username": "testuser",
    "ssh_hostname": "localhost",
    "ssh_port": 2222,
    "ssh_password": "testpass",
    "ssh_key": null,
    "ssh_key_passphrase": null
}

### Database Query Endpoints

### List queries
GET http://localhost:8000/api/queries/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODI0NTQxMn0.PuQMzGRbI7QK425PfGRO8VN-FK0MHqP2Wg6XFyajXdI

### Post New Query
POST http://localhost:8000/api/queries/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODI0NTQxMn0.PuQMzGRbI7QK425PfGRO8VN-FK0MHqP2Wg6XFyajXdI
Content-Type: application/json

{   
    "db_username": "t088503",
    "db_password": "hilaL250202",
    "db_tns": "localhost:1521/XE",
    "query_text": "SELECT * FROM example.test_data WHERE ROWNUM <= 5000"
}




### Get Query Stats
GET http://localhost:8000/api/queries/243
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODI0NTQxMn0.PuQMzGRbI7QK425PfGRO8VN-FK0MHqP2Wg6XFyajXdI

### Get Current Stats
GET http://localhost:8000/api/queries/stats/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODI0NTQxMn0.PuQMzGRbI7QK425PfGRO8VN-FK0MHqP2Wg6XFyajXdI

### Delete Query
DELETE http://localhost:8000/api/queries/88
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODI0NTQxMn0.PuQMzGRbI7QK425PfGRO8VN-FK0MHqP2Wg6XFyajXdI

### Batch Rerun Queries
POST http://localhost:8000/api/queries/batch/rerun
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODI0NTQxMn0.PuQMzGRbI7QK425PfGRO8VN-FK0MHqP2Wg6XFyajXdI
Content-Type: application/json

{
  "query_ids": [
    2,1
  ]
}