### Authentication Endpoints

### Register new user
POST http://localhost:8000/api/auth/register
Content-Type: application/json

{
    "email": "ugur@gmail.com",
    "password": "deneme",
    "full_name": "deneme"
}

### Login
POST http://localhost:8000/api/auth/login
Content-Type: application/x-www-form-urlencoded

username=ugur@gmail.com&password=deneme

### User Management Endpoints

### Get all users
GET http://localhost:8000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODA1MzkzN30.dm7QGa5PC41buBADGHxiFWmQ_6xtWtrDWrUhZHcZTZs

### Get specific user
GET http://localhost:8000/api/users/me/settings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODA1MzkzN30.dm7QGa5PC41buBADGHxiFWmQ_6xtWtrDWrUhZHcZTZs

### Update user
PUT http://localhost:8000/api/users/me/settings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODA1MzkzN30.dm7QGa5PC41buBADGHxiFWmQ_6xtWtrDWrUhZHcZTZs

{
    "export_location": "./exports",
    "export_type": "feather",
    "max_parallel_queries": 10
}

### Database Query Endpoints

### List queries
GET http://localhost:8000/api/queries/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODA1MzkzN30.dm7QGa5PC41buBADGHxiFWmQ_6xtWtrDWrUhZHcZTZs

### Post New Query
POST http://localhost:8000/api/queries/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODA1MzkzN30.dm7QGa5PC41buBADGHxiFWmQ_6xtWtrDWrUhZHcZTZs
Content-Type: application/json

{   
    "db_username": "t088503",
    "db_password": "hilaL250202",
    "db_tns": "localhost:1521/XE",
    "query_text": "SELECT * FROM example.test_data WHERE ROWNUM <= 950000",
    "export_type": "feather"
}

### Get Query Stats
GET http://localhost:8000/api/queries/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODA1MzkzN30.dm7QGa5PC41buBADGHxiFWmQ_6xtWtrDWrUhZHcZTZs

### Get Current Stats
GET http://localhost:8000/api/queries/stats/current
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODA1MzkzN30.dm7QGa5PC41buBADGHxiFWmQ_6xtWtrDWrUhZHcZTZs

### Delete Query
DELETE http://localhost:8000/api/queries/88
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1Z3VyQGdtYWlsLmNvbSIsImV4cCI6MTczODA1MzkzN30.dm7QGa5PC41buBADGHxiFWmQ_6xtWtrDWrUhZHcZTZs